### ISSUE TITLE
[Fabric 1.21] v9.0.0: Crashing due to "ReloadSubcommand" is implementing an abstract class

### ISSUE THREAD

**Issue by ghost** [Boxadactle/DebugKeybind#5]
By reading the error report below - and seeing the code in [here](https://github.com/Boxadactle/DebugKeybind/blob/a8b0a258237d6297402d3fcde09d8aaad94c7d94/common/src/main/java/dev/boxadactle/debugkeybind/command/ReloadSubcommand.java#L9) - I assume the crashing is due to `ReloadSubcommand` *implements* an abstract class and it's not possible to do in Java. I'm not a Java expert but, by searching, I think we can use `exports` instead? Thank you in advance.

```java
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2024-07-20 01:22:26
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'debugkeybind'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IncompatibleClassChangeError: class dev.boxadactle.debugkeybind.command.ReloadSubcommand can not implement dev.boxadactle.boxlib.command.api.BClientSubcommand, because it is not an interface (dev.boxadactle.boxlib.command.api.BClientSubcommand is in unnamed module of loader net.fabric
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at dev.boxadactle.debugkeybind.DebugKeybindMain.init(DebugKeybindMain.java:29)
	at dev.boxadactle.debugkeybind.fabric.DebugKeybindFabric.onInitializeClient(DebugKeybindFabric.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
```

**Comment by Boxadactle** [comment]
Hello, I accidentally removed a feature that this mod is trying to use from my library mod. This has been fixed in a later version: https://modrinth.com/mod/boxlib/version/iNlfgk9f
